version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-container
    restart: unless-stopped
    environment:
      POSTGRES_DB: gereciamento_tarefas
      POSTGRES_USER: gerenciamento_tarefas_jessica
      POSTGRES_PASSWORD: 1991
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: