INSERT INTO DEPARTAMENTO(ID, TITULO) VALUES (1, 'Finaceiro');
INSERT INTO DEPARTAMENTO(ID, TITULO) VALUES (2, 'Administrativo');
INSERT INTO DEPARTAMENTO(ID, TITULO) VALUES (3, 'Comercial');
INSERT INTO DEPARTAMENTO(ID, TITULO) VALUES (4, 'Juridico');
