INSERT INTO DEPARTAMENTO(ID, TITULO) VALUES (100, 'Finaceiro');
INSERT INTO DEPARTAMENTO(ID, TITULO) VALUES (101, 'Administrativo');
INSERT INTO DEPARTAMENTO(ID, TITULO) VALUES (102, 'Comercial');
INSERT INTO DEPARTAMENTO(ID, TITULO) VALUES (103, 'Juridico');


INSERT INTO PESSOA(ID, NOME, ID_DEPARTAMENTO)
VALUES (1, 'Maria Aparecida', 100);

INSERT INTO PESSOA(ID, NOME, ID_DEPARTAMENTO)
VALUES (2, 'José Henrique', 100);

INSERT INTO PESSOA(ID, NOME, ID_DEPARTAMENTO)
VALUES (3, 'Gustavo Lima', 101);


INSERT INTO TAREFA (ID, DESCRICAO, DURACAO, FINALIZADO, PRAZO, TITULO, PESSOA_ID, ID_DEPARTAMENTO)
VALUES (1, 'Entre em contato com nossos clientes', 30, FALSE, '2024-06-30',
'LIGAR PARA OS CLIENTES', 1, 100);

INSERT INTO TAREFA (ID, DESCRICAO, DURACAO, FINALIZADO, PRAZO, TITULO, PESSOA_ID, ID_DEPARTAMENTO)
VALUES (2, 'Conferir caixa', 15, FALSE, '2024-05-30',
'CONFERIR CAIXA', 1, 101);

INSERT INTO TAREFA (ID, DESCRICAO, DURACAO, FINALIZADO, PRAZO, TITULO, PESSOA_ID, ID_DEPARTAMENTO)
VALUES (3, 'Pagar os colaboradores', 30, FALSE, '2024-06-30',
'PAGAR OS COLABORADORES', 3, 101);

INSERT INTO TAREFA (ID, DESCRICAO, DURACAO, FINALIZADO, PRAZO, TITULO, PESSOA_ID)
VALUES (4, 'Emitir os holerites', 30, FALSE, '2024-04-30',
'EMIÇÃO DOS HOLERITES', NULL);

INSERT INTO TAREFA (ID, DESCRICAO, DURACAO, FINALIZADO, PRAZO, TITULO, PESSOA_ID)
VALUES (5, 'Ação', 30, FALSE, '2024-03-30',
'AÇÃO 27676-98', NULL);

INSERT INTO TAREFA (ID, DESCRICAO, DURACAO, FINALIZADO, PRAZO, TITULO, PESSOA_ID)
VALUES (6, 'Postagem na rede social no Instagram', 30, FALSE, '2024-03-30',
'POSTAR', NULL);

