INSERT INTO PESSOA(ID, NOME, DEPARTAMENTO)
VALUES (1, 'Maria Aparecida', 'COMERCIAL');

INSERT INTO PESSOA(ID, NOME, DEPARTAMENTO)
VALUES (2, 'José Henrique', 'COMERCIAL');

INSERT INTO PESSOA(ID, NOME, DEPARTAMENTO)
VALUES (3, 'Gustavo Lima', 'FINANCEIRO');

