INSERT INTO TAREFA (ID, DESCRICAO, DURACAO, FINALIZADO, PRAZO, TITULO, PESSOA_ID)
VALUES (1, 'Entre em contato com nossos clientes', 30, FALSE, '2024-06-30',
'LIGAR PARA OS CLIENTES', 1);

INSERT INTO TAREFA (ID, DESCRICAO, DURACAO, FINALIZADO, PRAZO, TITULO, PESSOA_ID)
VALUES (2, 'Conferir caixa', 15, FALSE, '2024-05-30',
'CONFERIR CAIXA', 1);

INSERT INTO TAREFA (ID, DESCRICAO, DURACAO, FINALIZADO, PRAZO, TITULO, PESSOA_ID)
VALUES (3, 'Pagar os colaboradores', 30, FALSE, '2024-06-30',
'PAGAR OS COLABORADORES', 3);

INSERT INTO TAREFA (ID, DESCRICAO, DURACAO, FINALIZADO, PRAZO, TITULO, PESSOA_ID)
VALUES (4, 'Emitir os holerites', 30, FALSE, '2024-04-30',
'EMIÇÃO DOS HOLERITES', NULL);

INSERT INTO TAREFA (ID, DESCRICAO, DURACAO, FINALIZADO, PRAZO, TITULO, PESSOA_ID)
VALUES (5, 'Ação', 30, FALSE, '2024-03-30',
'AÇÃO 27676-98', NULL);

INSERT INTO TAREFA (ID, DESCRICAO, DURACAO, FINALIZADO, PRAZO, TITULO, PESSOA_ID)
VALUES (6, 'Postagem na rede social no Instagram', 30, FALSE, '2024-03-30',
'POSTAR', NULL);



