INSERT INTO TAREFA (ID, DEPARTAMENTO, DESCRICAO, DURACAO, FINALIZADO, PRAZO, TITULO, PESSOA_ID)
VALUES (1, 'COMERCIAL', 'Entre em contato com nossos clientes', 30, FALSE, '2024-06-30',
'LIGAR PARA OS CLIENTES', 1);


INSERT INTO TAREFA (ID, DEPARTAMENTO, DESCRICAO, DURACAO, FINALIZADO, PRAZO, TITULO, PESSOA_ID)
VALUES (2, 'COMERCIAL', 'Conferir caixa', 30, FALSE, '2024-06-30',
'CONFERIR CAIXA', 1);

INSERT INTO TAREFA (ID, DEPARTAMENTO, DESCRICAO, DURACAO, FINALIZADO, PRAZO, TITULO, PESSOA_ID)
VALUES (3, 'FINANCEIRO', 'Pagar os colaboradores', 30, FALSE, '2024-06-30',
'PAGAR OS COLABORADORES', 3);



